# frozen_string_literal: true

module Auth0
  module Types
    module ConnectionStrategyEnum
      extend Auth0::Internal::Types::Enum

      AD = "ad"
      ADFS = "adfs"
      AMAZON = "amazon"
      APPLE = "apple"
      DROPBOX = "dropbox"
      BITBUCKET = "bitbucket"
      AUTH0OIDC = "auth0-oidc"
      AUTH0 = "auth0"
      BAIDU = "baidu"
      BITLY = "bitly"
      BOX = "box"
      CUSTOM = "custom"
      DACCOUNT = "daccount"
      DWOLLA = "dwolla"
      EMAIL = "email"
      EVERNOTE_SANDBOX = "evernote-sandbox"
      EVERNOTE = "evernote"
      EXACT = "exact"
      FACEBOOK = "facebook"
      FITBIT = "fitbit"
      GITHUB = "github"
      GOOGLE_APPS = "google-apps"
      GOOGLE_OAUTH2 = "google-oauth2"
      INSTAGRAM = "instagram"
      IP = "ip"
      LINE = "line"
      LINKEDIN = "linkedin"
      OAUTH1 = "oauth1"
      OAUTH2 = "oauth2"
      OFFICE365 = "office365"
      OIDC = "oidc"
      OKTA = "okta"
      PAYPAL = "paypal"
      PAYPAL_SANDBOX = "paypal-sandbox"
      PINGFEDERATE = "pingfederate"
      PLANNINGCENTER = "planningcenter"
      SALESFORCE_COMMUNITY = "salesforce-community"
      SALESFORCE_SANDBOX = "salesforce-sandbox"
      SALESFORCE = "salesforce"
      SAMLP = "samlp"
      SHAREPOINT = "sharepoint"
      SHOPIFY = "shopify"
      SHOP = "shop"
      SMS = "sms"
      SOUNDCLOUD = "soundcloud"
      THIRTYSEVENSIGNALS = "thirtysevensignals"
      TWITTER = "twitter"
      UNTAPPD = "untappd"
      VKONTAKTE = "vkontakte"
      WAAD = "waad"
      WEIBO = "weibo"
      WINDOWSLIVE = "windowslive"
      WORDPRESS = "wordpress"
      YAHOO = "yahoo"
      YANDEX = "yandex"
      AUTH0ADLDAP = "auth0-adldap"
    end
  end
end
