# frozen_string_literal: true

module Auth0
  module Types
    module ConnectionIdentityProviderEnum
      extend Auth0::Internal::Types::Enum

      AD = "ad"
      ADFS = "adfs"
      AMAZON = "amazon"
      APPLE = "apple"
      DROPBOX = "dropbox"
      BITBUCKET = "bitbucket"
      AUTH0OIDC = "auth0-oidc"
      AUTH0 = "auth0"
      BAIDU = "baidu"
      BITLY = "bitly"
      BOX = "box"
      CUSTOM = "custom"
      DACCOUNT = "daccount"
      DWOLLA = "dwolla"
      EMAIL = "email"
      EVERNOTE_SANDBOX = "evernote-sandbox"
      EVERNOTE = "evernote"
      EXACT = "exact"
      FACEBOOK = "facebook"
      FITBIT = "fitbit"
      GITHUB = "github"
      GOOGLE_APPS = "google-apps"
      GOOGLE_OAUTH2 = "google-oauth2"
      INSTAGRAM = "instagram"
      IP = "ip"
      LINE = "line"
      LINKEDIN = "linkedin"
      OAUTH1 = "oauth1"
      OAUTH2 = "oauth2"
      OFFICE365 = "office365"
      OIDC = "oidc"
      OKTA = "okta"
      PAYPAL = "paypal"
      PAYPAL_SANDBOX = "paypal-sandbox"
      PINGFEDERATE = "pingfederate"
      PLANNINGCENTER = "planningcenter"
      SALESFORCE_COMMUNITY = "salesforce-community"
      SALESFORCE_SANDBOX = "salesforce-sandbox"
      SALESFORCE = "salesforce"
      SAMLP = "samlp"
      SHAREPOINT = "sharepoint"
      SHOPIFY = "shopify"
      SHOP = "shop"
      SMS = "sms"
      SOUNDCLOUD = "soundcloud"
      THIRTYSEVENSIGNALS = "thirtysevensignals"
      TWITTER = "twitter"
      UNTAPPD = "untappd"
      VKONTAKTE = "vkontakte"
      WAAD = "waad"
      WEIBO = "weibo"
      WINDOWSLIVE = "windowslive"
      WORDPRESS = "wordpress"
      YAHOO = "yahoo"
      YANDEX = "yandex"
      NOTION_MCP = "notion-mcp"
      ASANA_MCP = "asana-mcp"
      ATLASSIAN_MCP = "atlassian-mcp"
      CLOUDFLARE_MCP = "cloudflare-mcp"
      DOCUSIGN_MCP = "docusign-mcp"
      FIGMA_MCP = "figma-mcp"
      GITLAB_MCP = "gitlab-mcp"
      GUSTO_MCP = "gusto-mcp"
      HEROKU_MCP = "heroku-mcp"
      HUBSPOT_MCP = "hubspot-mcp"
      INTERCOM_MCP = "intercom-mcp"
      LINEAR_MCP = "linear-mcp"
      PAGERDUTY_MCP = "pagerduty-mcp"
      SENTRY_MCP = "sentry-mcp"
      SLACK_MCP = "slack-mcp"
      SUPABASE_MCP = "supabase-mcp"
      VERCEL_MCP = "vercel-mcp"
      XERO_MCP = "xero-mcp"
    end
  end
end
