name: Publishes to RubyGems

#
# Publishes to RubyGems
#
# TODO: Remove once the common repo is public.
#

inputs:
  rubygems-token:
    required: true
  ruby-version:
    required: true

runs:
  using: composite

  steps:
    - name: Configure Ruby
      uses: ./.github/actions/setup
      with:
        ruby: ${{ inputs.ruby-version }}

    - name: Publish to RubyGems
      run: |
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ inputs.rubygems-token }}
