# frozen_string_literal: true

module Auth0
  module Users
    module Identities
      class Client
        # @param client [Auth0::Internal::Http::RawClient]
        #
        # @return [void]
        def initialize(client:)
          @client = client
        end

        # Link two user accounts together forming a primary and secondary relationship. On successful linking, the
        # endpoint returns the new array of the primary account identities.
        #
        # Note: There are two ways of invoking the endpoint:
        #
        # <ul>
        # <li>With the authenticated primary account's JWT in the Authorization header, which has the
        # <code>update:current_user_identities</code> scope:
        #     <pre>
        #       POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
        #       Authorization: "Bearer PRIMARY_ACCOUNT_JWT"
        #       {
        #         "link_with": "SECONDARY_ACCOUNT_JWT"
        #       }
        #     </pre>
        # In this case, only the <code>link_with</code> param is required in the body, which also contains the JWT
        # obtained upon the secondary account's authentication.
        #   </li>
        #   <li>With a token generated by the API V2 containing the <code>update:users</code> scope:
        #     <pre>
        #     POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
        #     Authorization: "Bearer YOUR_API_V2_TOKEN"
        #     {
        #       "provider": "SECONDARY_ACCOUNT_PROVIDER",
        #       "connection_id": "SECONDARY_ACCOUNT_CONNECTION_ID(OPTIONAL)",
        #       "user_id": "SECONDARY_ACCOUNT_USER_ID"
        #     }
        #     </pre>
        # In this case you need to send <code>provider</code> and <code>user_id</code> in the body. Optionally you can
        # also send the <code>connection_id</code> param which is suitable for identifying a particular database
        # connection for the 'auth0' provider.
        #   </li>
        # </ul>
        #
        # @param request_options [Hash]
        # @param params [Auth0::Users::Identities::Types::LinkUserIdentityRequestContent]
        # @option request_options [String] :base_url
        # @option request_options [Hash{String => Object}] :additional_headers
        # @option request_options [Hash{String => Object}] :additional_query_parameters
        # @option request_options [Hash{String => Object}] :additional_body_parameters
        # @option request_options [Integer] :timeout_in_seconds
        # @option params [String] :id
        #
        # @return [Array[Auth0::Types::UserIdentity]]
        def link(request_options: {}, **params)
          params = Auth0::Internal::Types::Utils.normalize_keys(params)
          request_data = Auth0::Users::Identities::Types::LinkUserIdentityRequestContent.new(params).to_h
          non_body_param_names = ["id"]
          body = request_data.except(*non_body_param_names)

          request = Auth0::Internal::JSON::Request.new(
            base_url: request_options[:base_url],
            method: "POST",
            path: "users/#{URI.encode_uri_component(params[:id].to_s)}/identities",
            body: body,
            request_options: request_options
          )
          begin
            response = @client.send(request)
          rescue Net::HTTPRequestTimeout
            raise Auth0::Errors::TimeoutError
          end
          code = response.code.to_i
          return if code.between?(200, 299)

          error_class = Auth0::Errors::ResponseError.subclass_for_code(code)
          raise error_class.new(response.body, code: code)
        end

        # Unlink a specific secondary account from a target user. This action requires the ID of both the target user
        # and the secondary account.
        #
        # Unlinking the secondary account removes it from the identities array of the target user and creates a new
        # standalone profile for the secondary account. To learn more, review <a
        # href="https://auth0.com/docs/manage-users/user-accounts/user-account-linking/unlink-user-accounts">Unlink User
        # Accounts</a>.
        #
        # @param request_options [Hash]
        # @param params [Hash]
        # @option request_options [String] :base_url
        # @option request_options [Hash{String => Object}] :additional_headers
        # @option request_options [Hash{String => Object}] :additional_query_parameters
        # @option request_options [Hash{String => Object}] :additional_body_parameters
        # @option request_options [Integer] :timeout_in_seconds
        # @option params [String] :id
        # @option params [Auth0::Types::UserIdentityProviderEnum] :provider
        # @option params [String] :user_id
        #
        # @return [Array[Auth0::Types::DeleteUserIdentityResponseContentItem]]
        def delete(request_options: {}, **params)
          params = Auth0::Internal::Types::Utils.normalize_keys(params)
          request = Auth0::Internal::JSON::Request.new(
            base_url: request_options[:base_url],
            method: "DELETE",
            path: "users/#{URI.encode_uri_component(params[:id].to_s)}/identities/#{URI.encode_uri_component(params[:provider].to_s)}/#{URI.encode_uri_component(params[:user_id].to_s)}",
            request_options: request_options
          )
          begin
            response = @client.send(request)
          rescue Net::HTTPRequestTimeout
            raise Auth0::Errors::TimeoutError
          end
          code = response.code.to_i
          if code.between?(200, 299)
            Auth0::Types::DeleteUserIdentityResponseContent.load(response.body)
          else
            error_class = Auth0::Errors::ResponseError.subclass_for_code(code)
            raise error_class.new(response.body, code: code)
          end
        end
      end
    end
  end
end
