# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 4.0"
gem "rackup", "~> 2.1"
gem "puma", "~> 6.0"
gem "auth0", path: "../.."
gem "dotenv", "~> 3.0"
gem "jwt", "~> 2.7"
