name: Semgrep

on:
  pull_request: {}

  push:
    branches:
      - master
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.repository_owner == 'auth0')
    
    steps:
      - uses: actions/checkout@v3

      - if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
